spring:
  datasource:
    url: jdbc:postgresql://dpg-d80pb6btqb8s738dp7hg-a.ohio-postgres.render.com
    username: user
    password: YmdIRALnym4OKFctGiSjsNALlN7LL09W
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false